package com.nsi.invisee.otp.domain;
// Generated Sep 27, 2017 2:18:23 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailAgentAccess generated by hbm2java
 */
@Entity
@Table(name = "api_otp_access_2")
public class OtpApiAccess implements java.io.Serializable {

    private OtpApiAccessId id;
    private OtpApi otpApi;

    public OtpApiAccess() {
    }

    public OtpApiAccess(OtpApiAccessId id, OtpApi otpApi) {
        this.id = id;
        this.otpApi = otpApi;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "code", column = @Column(name = "code", nullable = false)), 
        @AttributeOverride(name = "ipAddress", column = @Column(name = "ip_address", nullable = false, length = 20))})
    public OtpApiAccessId getId() {
        return this.id;
    }

    public void setId(OtpApiAccessId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "code", nullable = false, insertable = false, updatable = false)
    public OtpApi getOtpApi() {
        return this.otpApi;
    }

    public void setOtpApi(OtpApi otpApi) {
        this.otpApi = otpApi;
    }

}
