package com.nsi.invisee.otp.domain;
// Generated Sep 27, 2017 2:18:23 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailAgent generated by hbm2java
 */
@Entity
@Table(name = "api_otp_token_2")
public class OtpApiToken implements java.io.Serializable {

    private long id;
    private OtpApi otpApi;
    private String trxId;
    private String type;
    private String stan;
    private String token;
    private String ipAddress;
    private Integer session;
    private Integer status;
    private Date dateSend;
    private Date dateUsed;
    private Date expired;

    public OtpApiToken() {
    }
    
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "log_generator")
    @SequenceGenerator(name = "log_generator", sequenceName = "otp_log_token_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "code", nullable = false)
    public OtpApi getOtpApi() {
        return otpApi;
    }

    public void setOtpApi(OtpApi otpApi) {
        this.otpApi = otpApi;
    }

    @Column(name = "trx_id")
    public String getTrxId() {
        return trxId;
    }

    public void setTrxId(String trxId) {
        this.trxId = trxId;
    }

    @Column(name = "ip_address")    
    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
    @Column(name = "type")    
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "stan")    
    public String getStan() {
        return stan;
    }

    public void setStan(String stan) {
        this.stan = stan;
    }

    @Column(name = "token")    
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Column(name = "time_session")    
    public Integer getSession() {
        return session;
    }

    public void setSession(Integer session) {
        this.session = session;
    }

    @Column(name = "status")    
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_send", nullable = false, length = 29)
    public Date getDateSend() {
        return dateSend;
    }

    public void setDateSend(Date dateSend) {
        this.dateSend = dateSend;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_used", length = 29)
    public Date getDateUsed() {
        return dateUsed;
    }

    public void setDateUsed(Date dateUsed) {
        this.dateUsed = dateUsed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_expired", nullable = false, length = 29) 
    public Date getExpired() {
        return expired;
    }

    public void setExpired(Date expired) {
        this.expired = expired;
    }
    
}
