package com.nsi.invisee.otp.domain;
// Generated Oct 9, 2017 11:10:52 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtpLog generated by hbm2java
 */
@Entity
@Table(name = "api_otp_log_mitra_2")
public class OtpApiLogMitra implements java.io.Serializable {

    private long id;
    private OtpApiLogTrx otpApiLogTrx;
    private Date dateTime;
    private String request;
    private String url;
    private String response;

    public OtpApiLogMitra() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "log_generator")
    @SequenceGenerator(name = "log_generator", sequenceName = "otp_log_mitra_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "log_trx_id", nullable = false)
    public OtpApiLogTrx getOtpApiLogTrx() {
        return otpApiLogTrx;
    }

    public void setOtpApiLogTrx(OtpApiLogTrx otpApiLogTrx) {
        this.otpApiLogTrx = otpApiLogTrx;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_time", nullable = false, length = 29)
    public Date getDateTime() {
        return this.dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    @Column(name = "request_url", nullable = false)
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "request_body", nullable = false)
    public String getRequest() {
        return this.request;
    }

    public void setRequest(String request) {
        this.request = request;
    }

    @Column(name = "response_body")
    public String getResponse() {
        return this.response;
    }

    public void setResponse(String response) {
        this.response = response;
    }

}
