package com.nsi.invisee.otp.domain;
// Generated Sep 27, 2017 2:18:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmailAgent generated by hbm2java
 */
@Entity
@Table(name = "api_otp_config_2")
public class OtpApi implements java.io.Serializable {

    private String code;
    private String codeEmail;
    private String codeSms;
    private boolean statusEmail;
    private boolean statusSms;

    public OtpApi() {
    }
    
    @Id
    @Column(name = "code", unique = true, nullable = false)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }    

    @Column(name = "code_email")
    public String getCodeEmail() {
        return codeEmail;
    }

    public void setCodeEmail(String codeEmail) {
        this.codeEmail = codeEmail;
    }

    @Column(name = "code_sms")    
    public String getCodeSms() {
        return codeSms;
    }

    public void setCodeSms(String codeSms) {
        this.codeSms = codeSms;
    }

    @Column(name = "status_email", nullable = false)    
    public boolean isStatusEmail() {
        return statusEmail;
    }

    public void setStatusEmail(boolean statusEmail) {
        this.statusEmail = statusEmail;
    }

    @Column(name = "status_sms", nullable = false)        
    public boolean isStatusSms() {
        return statusSms;
    }

    public void setStatusSms(boolean statusSms) {
        this.statusSms = statusSms;
    }
}
