package com.nsi.invisee.otp.domain;
// Generated Sep 27, 2017 2:18:23 AM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailAgentAccessId generated by hbm2java
 */
@Embeddable
public class OtpApiAccessId implements java.io.Serializable {

    private String code;
    private String ipAddress;

    public OtpApiAccessId() {
    }

    public OtpApiAccessId(String code, String ipAddress) {
        this.code = code;
        this.ipAddress = ipAddress;
    }
    
    @Column(name = "code", nullable = false, length = 20)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "ip_address", nullable = false, length = 20)    
    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 43 * hash + Objects.hashCode(this.code);
        hash = 43 * hash + Objects.hashCode(this.ipAddress);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OtpApiAccessId other = (OtpApiAccessId) obj;
        if (!Objects.equals(this.code, other.code)) {
            return false;
        }
        if (!Objects.equals(this.ipAddress, other.ipAddress)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "OtpApiAccessId{" + "code=" + code + ", ipAddress=" + ipAddress + '}';
    }
    
}
