package com.nsi.invisee.otp.domain;
// Generated Sep 27, 2017 2:18:23 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailAgentAccess generated by hbm2java
 */
@Entity
@Table(name = "api_otp_template_email_2")
public class OtpApiTemplateEmail implements java.io.Serializable {

    private OtpApiTemplateId id;
    private OtpApi otpApi;
    private String subject;
    private String content;

    public OtpApiTemplateEmail() {
    }

    public OtpApiTemplateEmail(OtpApiTemplateId id, OtpApi otpApi) {
        this.id = id;
        this.otpApi = otpApi;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "code", column = @Column(name = "code", nullable = false)), 
        @AttributeOverride(name = "template", column = @Column(name = "template", nullable = false, length = 20))})
    public OtpApiTemplateId getId() {
        return this.id;
    }

    public void setId(OtpApiTemplateId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "code", nullable = false, insertable = false, updatable = false)
    public OtpApi getOtpApi() {
        return this.otpApi;
    }

    public void setOtpApi(OtpApi otpApi) {
        this.otpApi = otpApi;
    }

    @Column(name = "subject")
    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Column(name = "content")
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
