package com.nsi.invisee.otp.domain;
// Generated Sep 27, 2017 2:18:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmailAgent generated by hbm2java
 */
@Entity
@Table(name = "api_otp_parameter_2")
public class OtpApiParameter implements java.io.Serializable {

    private String code;
    private String value;

    public OtpApiParameter() {
    }
    
    @Id
    @Column(name = "code", unique = true, nullable = false)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }    

    @Column(name = "value")
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
