package com.nsi.invisee.otp.domain;
// Generated Sep 27, 2017 2:18:23 AM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailAgentAccessId generated by hbm2java
 */
@Embeddable
public class OtpApiTemplateId implements java.io.Serializable {

    private String code;
    private String template;

    public OtpApiTemplateId() {
    }

    public OtpApiTemplateId(String code, String template) {
        this.code = code;
        this.template = template;
    }
    
    @Column(name = "code", nullable = false, length = 20)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "template", nullable = false, length = 20)    
    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 43 * hash + Objects.hashCode(this.code);
        hash = 43 * hash + Objects.hashCode(this.template);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OtpApiTemplateId other = (OtpApiTemplateId) obj;
        if (!Objects.equals(this.code, other.code)) {
            return false;
        }
        if (!Objects.equals(this.template, other.template)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "OtpApiTemplateId{" + "code=" + code + ", template=" + template + '}';
    }
    
}
